# Generated by Django 4.1.7 on 2023-03-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=300)),
                ('treatment', models.CharField(max_length=13)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'disease',
            },
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('step', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'symptoms',
            },
        ),
    ]
