# Generated by Django 4.1.7 on 2023-03-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetenaryweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='treatment',
            field=models.TextField(),
        ),
    ]
